apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: tool-svc
  namespace: scalable
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5000
  selector:
    app: tool
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tool
  namespace: scalable
spec:
  selector:
    matchLabels:
      app: tool
  replicas: 1
  template:
    metadata:
      labels:
        app: tool
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
      - image: docker.io/library/tool:v1
        name: tool-tcpreplay
        resources: {}
        volumeMounts:
        - name: shared-volume
          mountPath: /app/uploads
      dnsPolicy: ClusterFirst
      restartPolicy: Always
