apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: scalable
data:
  nginx.conf: |
    user nginx;
    error_log  /var/log/nginx/nginx-error.log;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080;
          server_name  localhost;
          access_log /var/log/nginx/nginx-access.log;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }


