apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: flask-test
  name: flask-test
spec:
  containers:
  - image: docker.io/library/distroless-flask:v1
    name: flask-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}