apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flask-test
  name: flask-test
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: flask-test
  type: LoadBalancer
status:
  loadBalancer: {}