apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: soc-svc
  namespace: scalable
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: soc
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: soc
  namespace: scalable
spec:
  selector:
    matchLabels:
      app: soc
  replicas: 3
  template:
    metadata:
      labels:
        app: soc
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: ingress
          persistentVolumeClaim:
            claimName: ingress-pvc
      containers:
      - image: docker.io/library/soc:v1
        name: soc
        resources: {}
        volumeMounts:
        - name: shared-volume
          mountPath: /app/uploads
        - name: ingress
          mountPath: /app/templates/logs/
      dnsPolicy: ClusterFirst
      restartPolicy: Always
