apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/scalable"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
  namespace: monitoring
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: soc-svc
  namespace: monitoring
  annotations:
    metallb.universe.tf/allow-shared-ip: "scalable"
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: soc
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soc
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: soc
  replicas: 1
  template:
    metadata:
      labels:
        app: soc
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: shared-pvc
        - name: ingress
          persistentVolumeClaim:
            claimName: ingress-pvc
      containers:
      - image: docker.io/library/soc:v1
        name: soc
        resources: {}
        volumeMounts:
        - name: shared-volume
          mountPath: /app/uploads
        - name: ingress
          mountPath: /app/templates/logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
